from successor_representation.agents.random_agent import SRRandomAgent
from successor_representation.agents.q_agent import SRQLearningAgent
from successor_representation.agents.tabular_counts import TabularCountsAgent